# Generated by Django 5.1.7 on 2025-04-02 08:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_meal_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Amount Paid($)')),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('failed', 'FAILED'), ('completed', 'COMPLETED')], default='pending', max_length=9, verbose_name='Delivery Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.meal')),
            ],
        ),
    ]
